jobs:
  include:
  - stage: Build
    name: Backend Tests
    language: elixir
    elixir: 1.10.2
    otp_release: 22.3
    services:
    - postgresql
    cache:
      directories:
      - backend/deps
      - backend/_build
    env:
    - MIX_ENV=test
    before_install: cd backend
    before_script: mix do ecto.create, ecto.migrate
    script: mix do compile --warnings-as-errors, coveralls.json
    after_success: bash <(curl -s https://codecov.io/bash)
  - name: Frontend Tests
    language: node_js
    node_js: "stable"
    cache:
      directories:
      - frontend/node_modules
    env:
    - CI=true
    before_install: cd frontend
    script: yarn test
  - name: Admin Frontend Tests
    language: node_js
    node_js: "stable"
    cache:
      directories:
      - admin-frontend/node_modules
    env:
    - CI=true
    before_install: cd admin-frontend
    script: yarn test
  - name: Credo
    language: elixir
    elixir: 1.10.2
    otp_release: 22.3
    cache:
      directories:
      - backend/deps
      - backend/_build
    before_install: cd backend
    before_script: mix compile
    script: mix credo --strict
