name: Backend Tests
on: push

jobs:
  backend:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
           
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2
          elixir-version: 1.10.2
      - run: cd backend
      - run: mix do deps.get, compile --warnings-as-errors, ecto.create, ecto.migrate
      - run: coveralls.json
