name: Tests
on: push

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest
    
    env: 
      TEST_DB_PASSWORD: postgres
      MIX_ENV: test

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
           
    steps:
      - uses: actions/checkout@master
      - name: Cache Backend Deps
        uses: actions/cache@master
        with:
          path: backend/deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/backend/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/setup-elixir@master
        with:
          otp-version: 22.3.3
          elixir-version: 1.10.3
      - uses: codecov/codecov-action@master
      - run: cd backend
      - run: mix do deps.get, compile --warnings-as-errors, ecto.create, ecto.migrate
      - run: coveralls.json

  credo:
    name: Credo
    runs-on: ubuntu-latest
           
    steps:
      - uses: actions/checkout@master
      - name: Cache Backend Deps
        uses: actions/cache@master
        with:
          path: backend/deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/backend/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-mix-
      - uses: actions/setup-elixir@master
        with:
          otp-version: 22.3.3
          elixir-version: 1.10.3
      - run: cd backend
      - run: mix do deps.get, compile --warnings-as-errors
      - run: credo

  frontend:
    name: Frontend
    runs-on: ubuntu-latest
           
    steps:
      - uses: actions/checkout@master
      - name: Cache Node Modules
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - uses: actions/setup-node@master
        with:
          node-version: 13.x
      - uses: codecov/codecov-action@master
      - run: cd frontend
      - run: npm install
      - run: npm run build
      - run: npm test -- --coverage

  admin-frontend:
    name: Admin Frontend
    runs-on: ubuntu-latest
           
    steps:
      - uses: actions/checkout@master
      - name: Cache Node Modules
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
      - uses: actions/setup-node@master
        with:
          node-version: 13.x
      - uses: codecov/codecov-action@master
      - run: cd admin-frontend
      - run: npm install
      - run: npm run build
      - run: npm test -- --coverage
