name: Tests
on: push

jobs:
  backend:
    name: Backend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [22.3.3]
        elixir: [1.10.3]

    defaults:
      run:
        working-directory: backend

    env: 
      TEST_DB_PASSWORD: postgres
      MIX_ENV: test

    services:
      db:
        image: postgres:11
        ports: ['5432:5432']
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-elixir@master
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache Backend Deps
        uses: actions/cache@master
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Cache Backend Build
        uses: actions/cache@master
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix do deps.get, compile --warnings-as-errors, ecto.create, ecto.migrate

      - run: mix coveralls.json

      - uses: codecov/codecov-action@master

  credo:
    name: Credo
    runs-on: ubuntu-latest

    strategy:
      matrix:
        otp: [22.3.3]
        elixir: [1.10.3]

    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-elixir@master
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}

      - name: Cache Backend Deps
        uses: actions/cache@master
        id: deps-cache
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Cache Backend Build
        uses: actions/cache@master
        id: build-cache
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - run: mix do deps.get, compile --warnings-as-errors
      - run: mix credo

  frontend:
    name: Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 13.x

      - name: Cache Node Modules
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - run: npm install
      - run: npm run build
      - run: npm test -- --coverage
      - uses: codecov/codecov-action@master

  admin-frontend:
    name: Admin Frontend
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: admin-frontend

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: 13.x

      - name: Cache Node Modules
        uses: actions/cache@master
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-

      - run: npm install
      - run: npm run build
      - run: npm test -- --coverage
      - uses: codecov/codecov-action@master
